# env
env: button-press-v1
# Note: action repeat is not being used in metaworld
action_repeat: 4
# train
num_train_steps: 1000000
num_train_iters: 1
num_seed_steps: 1000
replay_buffer_capacity: 100000
seed: 2
# eval
eval_frequency: 25
ckpt_frequency: 1000
num_eval_episodes: 10
# misc
log_frequency_step: 10000
log_save_tb: true
save_video: true
device: cuda
remote_render: False
train_vid_interval: 10000
# observation
image_size: 84
image_pad: 4
frame_stack: 5
# global params
lr: 1e-3
batch_size: 32
reload_weights: False
env_resample_rate: 150
num_envs: 5
resample_env: True
apply_mod: True
# single_goal vs multi_goal
goal_mode: 'single_goal'
lowobs_append: True
internvention: ['type_1', 'type_2']
penalty_type: 'rex'
penalty_weight: 0.2237
penalty_anneal_iters: 3000

# agent configuration
agent:
  name: dbc
  cls: agents.dbc_agent.DBCAgent
  params:
    obs_shape: ??? # to be specified later
    action_shape: ???
    lstate_shape: ???
    action_range: ???
    device: ${device}
    encoder_cfg: ${encoder}
    critic_cfg: ${critic}
    actor_cfg: ${actor}
    discount: 0.99
    init_temperature: 0.1
    lr: ${lr}
    actor_update_frequency: 2
    critic_tau: 0.01
    critic_target_update_frequency: 2
    batch_size: ${batch_size}
    penalty_type: ${penalty_type}
    penalty_weight: ${penalty_weight}
    penalty_anneal_iters: ${penalty_anneal_iters}

critic:
  cls: modules.Critic
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    lstate_shape: ${agent.params.lstate_shape}
    hidden_dim: 1024
    hidden_depth: 2
    
actor:
  cls: modules.Actor
  params:
    encoder_cfg: ${agent.params.encoder_cfg}
    action_shape: ${agent.params.action_shape}
    lstate_shape: ${agent.params.lstate_shape}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds: [-10, 2]
    
encoder:
  cls: modules.Encoder
  params:
      obs_shape: ${agent.params.obs_shape}
      feature_dim: 50

# hydra configuration
hydra:
  run:
    dir: ./runs/${now:%Y.%m.%d}/${env}_${agent.name}_${hydra.job.override_dirname}/seed=${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed